import React, { useState } from 'react';
import {
  Bot,
  Send,
  Sparkles,
  Database,
  FileText,
  ShieldCheck,
  CheckCircle,
  HelpCircle,
  Download,
  RefreshCw,
  ArrowRight,
  Info
} from 'lucide-react';
import { aiService } from '../../services/apiServices';
import { AIAnalysisResult } from '../../types';
import { DataTrustBadge } from '../common/DataTrustBadge';

interface Message {
  id: string;
  sender: 'user' | 'assistant';
  text?: string;
  analysis?: AIAnalysisResult;
  timestamp: string;
}

export const LandIntelligenceAI: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'welcome',
      sender: 'assistant',
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      analysis: {
        summary: 'Greetings. I am Land Intelligence AI, the analytical copilot for the National Land Intelligence & Governance Platform. How may I assist your spatial research, dataset discovery, or cadastral policy evaluation today?',
        evidence: 'Synchronized with 184M national cadastral parcels, ISRO decadal multi-spectral classifications, and peer-reviewed land governance frameworks.',
        dataSources: ['National Cadastral Geodatabase', 'Survey of India CORS Network', 'eCourts NJDG Civil Index'],
        confidence: 96,
        limitations: 'Demo response based on simulated knowledge for Smart India Hackathon 2026.',
        suggestedNextSteps: [
          'Ask about peri-urban farmland conversion trends',
          'Search for dispute mitigation case studies',
          'Explore CORS high-precision survey guidelines'
        ],
        timestamp: new Date().toISOString()
      }
    }
  ]);
  const [inputText, setInputText] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);

  const samplePrompts = [
    'Show land-use change trends in peri-urban corridors',
    'Find datasets related to urban expansion and farmland loss',
    'What factors are associated with cadastral boundary disputes?',
    'Find relevant case studies on automated mutation',
    'Which datasets can support rural micro-loan research?'
  ];

  const handleSendMessage = async (textToSend?: string) => {
    const query = (textToSend || inputText).trim();
    if (!query || isProcessing) return;

    const userMsg: Message = {
      id: `u-${Date.now()}`,
      sender: 'user',
      text: query,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setMessages((prev) => [...prev, userMsg]);
    setInputText('');
    setIsProcessing(true);

    try {
      const response = await aiService.queryAssistant(query);
      const assistantMsg: Message = {
        id: `a-${Date.now()}`,
        sender: 'assistant',
        analysis: response,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };
      setMessages((prev) => [...prev, assistantMsg]);
    } catch (err) {
      console.error(err);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleExportBrief = (analysis: AIAnalysisResult) => {
    const briefText = `NATIONAL LAND INTELLIGENCE PLATFORM - RESEARCH BRIEF
Generated by Land Intelligence AI (Smart India Hackathon 2026)
Date: ${new Date(analysis.timestamp).toLocaleString()}

========================================
1. SUMMARY
========================================
${analysis.summary}

========================================
2. EVIDENCE
========================================
${analysis.evidence}

========================================
3. DATA SOURCES
========================================
${analysis.dataSources.map((s) => '- ' + s).join('\n')}

========================================
4. CONFIDENCE & LIMITATIONS
========================================
Confidence: ${analysis.confidence}%
Limitations: ${analysis.limitations}

========================================
5. RECOMMENDED NEXT STEPS
========================================
${analysis.suggestedNextSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}
`;

    const blob = new Blob([briefText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Land_Intelligence_Research_Brief_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4 pb-12 animate-in fade-in duration-200">
      {/* Header Banner */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-lg flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-400">
              <Bot className="w-5 h-5" />
            </div>
            <h2 className="text-lg font-bold text-slate-100">
              Land Intelligence AI Research Assistant
            </h2>
          </div>
          <p className="text-xs text-slate-400 mt-1 max-w-2xl leading-relaxed">
            Multi-modal GIS reasoning, policy evidence extraction, and analytical brief generation powered by Gemini & cadastral knowledge models.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <DataTrustBadge score={96} source="Gemini 3.8 & Cadastral Engine" />
        </div>
      </div>

      {/* Quick Prompts Bar */}
      <div className="flex items-center gap-2 overflow-x-auto pb-1">
        <span className="text-xs text-slate-500 uppercase tracking-wider font-semibold shrink-0">
          Suggested:
        </span>
        {samplePrompts.map((prompt) => (
          <button
            key={prompt}
            onClick={() => handleSendMessage(prompt)}
            className="px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-slate-300 hover:text-emerald-400 border border-slate-800 text-xs whitespace-nowrap transition"
          >
            {prompt}
          </button>
        ))}
      </div>

      {/* Main Conversation Container */}
      <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 shadow-xl min-h-[480px] max-h-[620px] flex flex-col justify-between overflow-hidden">
        {/* Messages Stream */}
        <div className="flex-1 overflow-y-auto space-y-4 pr-2">
          {messages.map((msg) => {
            const isUser = msg.sender === 'user';
            return (
              <div
                key={msg.id}
                className={`flex gap-3 ${isUser ? 'justify-end' : 'justify-start'}`}
              >
                {!isUser && (
                  <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 flex items-center justify-center shrink-0 mt-1">
                    <Bot className="w-4 h-4" />
                  </div>
                )}

                <div
                  className={`max-w-2xl rounded-xl p-4 text-xs leading-relaxed space-y-3 ${
                    isUser
                      ? 'bg-emerald-600 text-slate-950 font-medium rounded-tr-none'
                      : 'bg-slate-900 border border-slate-800 text-slate-200 rounded-tl-none shadow-md'
                  }`}
                >
                  {isUser ? (
                    <div>{msg.text}</div>
                  ) : msg.analysis ? (
                    <div className="space-y-3">
                      {/* Structured Response Format (Prompt Mandate) */}
                      <div>
                        <span className="text-[10px] font-mono uppercase tracking-wider font-bold text-emerald-400 block mb-1">
                          SUMMARY
                        </span>
                        <p className="text-slate-100 text-sm leading-relaxed font-sans">
                          {msg.analysis.summary}
                        </p>
                      </div>

                      <div className="pt-2 border-t border-slate-800">
                        <span className="text-[10px] font-mono uppercase tracking-wider font-bold text-cyan-400 block mb-1">
                          EVIDENCE & GROUND TRUTH
                        </span>
                        <p className="text-slate-300 leading-relaxed">
                          {msg.analysis.evidence}
                        </p>
                      </div>

                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-2 border-t border-slate-800">
                        <div>
                          <span className="text-[10px] font-mono uppercase tracking-wider font-bold text-indigo-400 block mb-1">
                            DATA SOURCES
                          </span>
                          <ul className="list-disc list-inside text-slate-400 space-y-0.5">
                            {msg.analysis.dataSources.map((ds, i) => (
                              <li key={i}>{ds}</li>
                            ))}
                          </ul>
                        </div>

                        <div>
                          <span className="text-[10px] font-mono uppercase tracking-wider font-bold text-amber-400 block mb-1">
                            CONFIDENCE & LIMITATIONS
                          </span>
                          <div className="text-emerald-400 font-mono font-semibold">
                            Prototype Analytical Confidence: {msg.analysis.confidence}%
                          </div>
                          <p className="text-[11px] text-slate-500 italic mt-0.5">
                            {msg.analysis.limitations}
                          </p>
                        </div>
                      </div>

                      <div className="pt-2 border-t border-slate-800 space-y-1">
                        <span className="text-[10px] font-mono uppercase tracking-wider font-bold text-emerald-400 block">
                          SUGGESTED NEXT STEPS
                        </span>
                        <div className="space-y-1">
                          {msg.analysis.suggestedNextSteps.map((step, idx) => (
                            <div key={idx} className="flex items-center gap-2 text-slate-300">
                              <CheckCircle className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                              <span>{step}</span>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Brief Export Button */}
                      <div className="pt-2 border-t border-slate-800 flex items-center justify-between text-[11px] text-slate-500 font-mono">
                        <span>{msg.timestamp}</span>
                        <button
                          onClick={() => handleExportBrief(msg.analysis!)}
                          className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-emerald-400 hover:text-emerald-300 rounded flex items-center gap-1 font-sans transition"
                        >
                          <Download className="w-3.5 h-3.5" />
                          <span>Export Research Brief</span>
                        </button>
                      </div>
                    </div>
                  ) : null}
                </div>
              </div>
            );
          })}

          {isProcessing && (
            <div className="flex gap-3">
              <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 flex items-center justify-center shrink-0">
                <Bot className="w-4 h-4 animate-spin" />
              </div>
              <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 text-xs text-slate-400 flex items-center gap-2">
                <RefreshCw className="w-3.5 h-3.5 animate-spin text-emerald-400" />
                <span>Correlating spatial cadastre vectors and policy archives...</span>
              </div>
            </div>
          )}
        </div>

        {/* Input Form */}
        <div className="pt-3 border-t border-slate-800/80">
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleSendMessage();
            }}
            className="flex items-center gap-2"
          >
            <input
              type="text"
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              placeholder="Ask anything about land-use trends, dispute factors, datasets, or policies..."
              className="flex-1 bg-slate-900 border border-slate-800 rounded-lg px-4 py-2.5 text-xs text-slate-200 placeholder:text-slate-500 focus:outline-none focus:border-emerald-500"
            />
            <button
              type="submit"
              disabled={isProcessing || !inputText.trim()}
              className="px-4 py-2.5 bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold rounded-lg transition disabled:opacity-40 flex items-center gap-1.5 shadow"
            >
              <span>Analyze</span>
              <Send className="w-3.5 h-3.5" />
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};
